title: "منهل صلاح الدين | بورتفوليو هندسي"
description: "طالب علوم حاسوب | مطور برمجيات"
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: null

title: "منهل | هندسة وابتكار"
description: "بورتفوليو تقني لمهندس المستقبل"
theme: jekyll-theme-cayman

# تمكين التنقل
nav:
  - name: "الرئيسية"
    link: "/"
  - name: "المشاريع"
    link: "/projects.md"
  - name: "عني"
    link: "/about.md"

