title: "منهل | هندسة وابتكار"
description: "بورتفوليو تقني لمهندس المستقبل"
theme: jekyll-theme-cayman

# تمكين التنقل
nav:
  - name: "الرئيسية"
    link: "/"
  - name: "المشاريع"
    link: "/projects.md"
  - name: "عني"
    link: "/about.md"

