theme: jekyll-theme-cayman

# إضافة قائمة تنقل (Navigation)
collections:
  pages:
    output: true
theme: jekyll-theme-cayman
<hr>
<footer style="text-align: center; color: #7f8c8d;">طتم البناء بواسطة منهل | 2026 | تقانه معلومات ب
</footer>
